/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./components/About.vue')['default']
    Binaural: typeof import('./components/Binaural.vue')['default']
    Breathing: typeof import('./components/Breathing.vue')['default']
    CategoryIcons: typeof import('./components/CategoryIcons.vue')['default']
    CategorySection: typeof import('./components/CategorySection.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    Countdown: typeof import('./components/Countdown.vue')['default']
    FloatingActions: typeof import('./components/FloatingActions.vue')['default']
    Hero: typeof import('./components/Hero.vue')['default']
    Isochronic: typeof import('./components/Isochronic.vue')['default']
    Lofi: typeof import('./components/Lofi.vue')['default']
    MediaSession: typeof import('./components/MediaSession.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    Modal: typeof import('./components/Modal.vue')['default']
    Notepad: typeof import('./components/Notepad.vue')['default']
    PlayButton: typeof import('./components/PlayButton.vue')['default']
    Pomodoro: typeof import('./components/Pomodoro.vue')['default']
    PomodoroSettings: typeof import('./components/PomodoroSettings.vue')['default']
    Presets: typeof import('./components/Presets.vue')['default']
    Share: typeof import('./components/Share.vue')['default']
    SharedMix: typeof import('./components/SharedMix.vue')['default']
    Shortcuts: typeof import('./components/Shortcuts.vue')['default']
    SleepTimer: typeof import('./components/SleepTimer.vue')['default']
    Snackbar: typeof import('./components/Snackbar.vue')['default']
    SoundCard: typeof import('./components/SoundCard.vue')['default']
    Source: typeof import('./components/Source.vue')['default']
    Todo: typeof import('./components/Todo.vue')['default']
  }
}
